### ISSUE TITLE
Question: Why does this work? 

### ISSUE THREAD

**Issue by Harmonyano** [Shpota/sha256check#2]
Hi, I found your answer in stackoverflow and it was really helpful. Could you be so kind to explain why this works though? I'm not very familiar with command line and am wondering how is 
```
sha256() {
    echo "$1 $2" | sha256sum --check
}
sha256 <expected-sha-256-sum> <name-of-the-file>
```
different from 
```
sha256sum --check <expected-sha-256-sum> <name-of-the-file>
```
Namely what is echo pipe doing here?

**Comment by Shpota** [comment]
Hi @Harmonyano,

I am glad my answer helped you. The `sha256sum --check` command consumes a text file containing the name of the file that is being verified and it's checksum. The pipe is used here to simulate reading from such a file.
